version: "2.3"

services:
  dspostgres:
    image: postgres:16.2
    container_name: dspostgres
    ports:
      - "5432:5432"
    volumes:
      - dspostgres:/var/lib/postgresql
      - dspostgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=digitalschool
    # command: postgres -c "listen_addresses='*'"
    restart: always

  dspgadmin:
    image: dpage/pgadmin4:latest
    container_name: dspgadmin
    ports:
      - "85:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=arton.bilalli1@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=artonbilalli
    volumes:
      - dspgadmin:/var/lib/pgadmin
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: dskeycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://dspostgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: digitalschool

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8080:8080"

volumes:
  dspostgres:
    external:
      true
  dspostgres-data:
    external:
      true
  dspgadmin:
    external:
      true

networks:
  default:
    external:
      true
    name: digitalschool